#!/usr/bin/env python

import re
import sys

from subprocess import Popen, PIPE

p = Popen("pylint -f parseable -r n %s" %
          sys.argv[1], shell=True, stdout=PIPE)
stdout = p.communicate()[0]
fullpattern = re.compile("(.*?):" # filename
                         "([0-9]):" # line number
                         "\[([EFIRWC])" # error type
                         "([0-9]+).*?\]" # the error number and context (unused)
                         "(.*)" # description
                         )
pattern = re.compile("\[([EFIRWC])" # error type
                     "([0-9]+).*?\]" # the error number and context (unused)
                     "(.*)" # description
                     )

for line in stdout.splitlines():
    line = line.strip()
    try:
        filename, linenum, line = line.split(':', 2)
    except Exception:
        pass
    match = pattern.match(line.strip())
    if match:
        errtype, errnum, description = match.groups()
        description = description.strip()
        if errtype in 'EF':
            msg = 'Error'
        else:
            msg = 'Warning'
        print "%s %s%s %s at %s line %s." % (msg, errtype, errnum,
                                             description, filename, linenum)
    else:
        print "Error F0000 Couldn't parse pylint output at %s line 1." % filename
        
